### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by LeStegii** [CrucibleMC/Grimoire-Mixins-1.7.10#8]
Please add a description for all of the patches, so we know what exactly they do.

**Comment by EverNife** [comment]
Related to: https://github.com/CrucibleMC/Grimoire-Mixins-1.7.10/issues/1

Most of the most important changes (like 90% os all changes) are on the README file, from there you can have a good idea of what most of these does.

**Comment by LeStegii** [comment]
I saw, but some of them don't (for example the tinkersdefense one), but I'm not talking about what a patch fixes, but how it does. For example if something got disabled, a permission got added and so on

**Comment by EverNife** [comment]
Sure thing, it would be really good.

The problem is that there is already a lot of fixes, documentating them all would take some time.

Almost every single mixing (at least the ones that i personally created) has a comment on the change saying how and why it fixes.

The trouble would be putting all these on a wiki, its something that must be done, fore sure!

This project is created using the Grimoire Legacy, when juan rewrites using the new grimoire, we might create a proper wiki, as it will be a lot easier.

**Comment by LeStegii** [comment]
Thanks ^^

**Comment by spannerman79** [comment]
Nto to mention what was talked about has already been covered via https://github.com/CrucibleMC/Grimoire-Mixins-1.7.10/issues/2 and https://github.com/CrucibleMC/Grimoire-Mixins-1.7.10/issues/1
